# Generated by Django 5.2.8 on 2025-12-23 05:00

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_socialmedia'),
        ('projects', '0002_sector_remove_project_gallery_images_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('cover_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='cover_image')),
                ('project_design_time', models.PositiveIntegerField(help_text='Days')),
                ('project_manufacture_time', models.PositiveIntegerField(help_text='Days')),
                ('project_installation_time', models.PositiveIntegerField(help_text='Days')),
                ('basic_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('premium_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('support_service', models.TextField()),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='service_list',
        ),
        migrations.RemoveField(
            model_name='project',
            name='service',
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='icon',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='icon'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_ksp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='projects.service'),
        ),
        migrations.AddField(
            model_name='service',
            name='type',
            field=models.CharField(choices=[('service', 'Service'), ('product', 'Product'), ('both', 'Both')], default='service', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='cover_image'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('ongoing', 'Ongoing'), ('future', 'Future')], max_length=20),
        ),
        migrations.RemoveField(
            model_name='project',
            name='team',
        ),
        migrations.AlterField(
            model_name='service',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='cover_image'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='PackageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.PositiveIntegerField()),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='projects.package')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectServiceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.service')),
            ],
            options={
                'unique_together': {('project', 'service')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='services',
            field=models.ManyToManyField(related_name='projects', through='projects.ProjectServiceLink', to='projects.service'),
        ),
        migrations.DeleteModel(
            name='ServiceList',
        ),
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.teammember'),
        ),
    ]
