# Generated by Django 4.2.26 on 2026-01-11 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_package_cover_image_alter_project_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.sector'),
        ),
    ]
