# Generated by Django 4.2.26 on 2026-02-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='is_default',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
