# Generated by Django 4.2.26 on 2026-02-16 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_shippingaddress_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_addresses', to='accounts.shippingzone'),
        ),
    ]
