# Generated by Django 4.2.26 on 2026-02-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsubmission',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
