# Generated by Django 4.2.26 on 2026-02-02 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0002_alter_order_status'),
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='couponusage',
                    name='order',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order'),
                ),
                migrations.AddField(
                    model_name='couponusage',
                    name='user',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
                migrations.AlterField(
                    model_name='couponusage',
                    name='coupon',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='coupons.coupon'),
                ),
            ],
            database_operations=[]  # Skip DB ops on Render because columns already exist
        )
    ]
