# Generated by Django 5.2.8 on 2025-11-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_attribute_attributevalue_category_inventory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='reserved_stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
