# Generated by Django 5.2.8 on 2025-12-22 10:52

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_alter_heroslide_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='brief',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
